name: CI

on:
  # Manually trigger workflow runs
  workflow_dispatch:

  # Trigger the workflow on push to the main branch
  push:
    branches: [ main ]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      # Check out your repository
      - uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Run Tests
      - name: Run Tests
        run: mvn -B test
